version: '3'
services:
  learning:
    image: dtomart/face-recognition-learning:1.0
    env_file:
    - .env
    build:
      context: ./celebrity-face-learn-app
    container_name: face-recognition-learning
    volumes:
    - ./105_classes_pins_dataset:/home/tartecki/face-recogn-system/105_classes_pins_dataset
    - ./Model:/home/tomart/Model
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [ gpu ]
  