version: '3'
services:
  learning:
    image: dtomart:face-recognition-learning
    env_file:
    - .env
    build:
      context: ./celebrity-face-learn-app
    container_name: face-recognition-learning
    volumes:
    - ./105_classes_pins_dataset:/home/tomart/105_classes_pins_dataset
    - ./Model:/home/tomart/Model
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [ gpu ]
  