kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  namespace: face-recogn
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 5080
      nodePort: 31000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: face-recogn
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
      - name: frontend
        image: dtomart/face-recognition-frontend:1.3
        ports:
        - containerPort: 5080
          protocol: TCP
        imagePullPolicy: Always
        env:
        - name: CONFIGURATION_NAME
          value: akri-udev-video
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frontend-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frontend-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: frontend-role
subjects:
  - kind: ServiceAccount
    name: frontend-sa
    namespace: face-recogn