apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: face-recogn
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: face-recogn-frontend
        image: dtomart/face-recognition-frontend:1.0
        ports:
        - containerPort: 5080
          protocol: TCP
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: face-recogn
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 5080
      targetPort: 5080
  type: NodePort

# kubectl expose deployment frontend-deployment --type=NodePort --port=5080