apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: face-recogn
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      volumes:
        - name: model-pv-storage
          persistentVolumeClaim:
            claimName: model-pv-claim
        - name: data-pv-storage
          persistentVolumeClaim:
            claimName: data-pv-claim
      containers:
      - name: face-recogn-app
        image: dtomart/face-recognition-app:1.0
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        volumeMounts:
          - mountPath: "/home/tartecki/face-recogn-system/Model"
            name: model-pv-storage
          - mountPath: "/home/tartecki/face-recogn-system/105_classes_pins_dataset"
            name: data-pv-storage
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: face-recogn
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - name: web
    protocol: TCP
    port: 5000
    targetPort: 5000
