apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: face-recogn
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - name: web
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: face-recogn
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      # volumes:
      # - name: aarch64-linux-gnu
      #   emptyDir: {}
      # - name: lib64
      #   emptyDir: {}
      volumes:
        - name: aarch64-linux-gnu
          hostPath:
            path: /usr/lib/aarch64-linux-gnu
            type: Directory
        - name: lib64
          hostPath:
            path: /usr/local/cuda/lib64
            type: Directory
      nodeSelector:
        gpu: jetson-nano
      containers:

      - name: webapp
        image: dtomart/face-recognition-app:1.5
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        volumeMounts:
          - mountPath: "/usr/lib/aarch64-linux-gnu" 
            name: aarch64-linux-gnu
          - mountPath: "/usr/local/cuda/lib64" 
            name: lib64
        env:
        - name: CAMERA_SOURCE_SVC
          valueFrom:
            configMapKeyRef:
              name: cluster-configuration
              key: CAMERA_SOURCE_SVC

#       - name: lib64-sidecar
#         image: kiwigrid/k8s-sidecar:1.19.2
#         imagePullPolicy: IfNotPresent
#         volumeMounts:
#         - name: lib64
#         - mountPath: "/usr/local/cuda/lib64/" 
#         env:
#         - name: LABEL
#           value: "gpu"
#         - name: FOLDER
#           value: "/usr/local/cuda/lib64/"

#       - name: aarch64-linux-gnu-sidecar
#         image: kiwigrid/k8s-sidecar:1.19.2
#         imagePullPolicy: IfNotPresent
#         volumeMounts:
#         - name: aarch64-linux-gnu
#           mountPath: /usr/lib/aarch64-linux-gnu/
#         env:
#         - name: LABEL
#           value: "gpu"
#         - name: FOLDER
#           value: "/usr/lib/aarch64-linux-gnu/"
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: gpu-configuration
#   namespace: face-recogn
#   labels:
#     gpu: jetson-nano
# data:
#   aarch64-linux-gnu: "/usr/lib/aarch64-linux-gnu"
#   lib64: /usr/local/cuda/lib64
  
