apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
  # namespace: face-recogn
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Gi