apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pv-claim
  namespace: face-recogn
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi