apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv-volume
  # namespace: face-recogn
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/tartecki/face-recogn-system/Model"