apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv-volume
  # namespace: face-recogn
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  local:
    path: "/home/admin/projects/face-recogn/Model"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cm4-controlplane